MTDSA-20477 Hide v4 of self-employment-business-api
hmrc/self-employment-business-api pull request #227
Opened 2023-11-23 14:18 UTC by sean-flynn-HMRC

2023-11-23 14:35 UTC, KobithasanVasantharajah requested changes

2023-11-23 14:35 UTC, KobithasanVasantharajah commented on it/config/DocumentationControllerISpec.scala
> +    List(Version1, Version2, Version3 /*Version4*/).foreach { version =>
Here you've commented out "Version 4" but in the previous file you removed it. Should we remove it here too just to make it all consistent?

2023-11-24 07:46 UTC, abigail-houston-hmrc approved these changes

2023-11-24 10:35 UTC, KobithasanVasantharajah approved these changes

2023-11-24 10:36 UTC, merged