MTDSA-26544: Migrate List endpoint to Multi-Schema
hmrc/self-employment-business-api pull request #281
Opened 2024-09-23 08:24 UTC by KobithasanVasantharajah

2024-09-23 15:47 UTC, LouiseWong98 commented on app/v3/listPeriodSummaries/model/listPeriodSummaries/Def1_ListPeriodSummariesRequestData.scala
need to rename the root folder from listPeriodSummaries to request

2024-10-01 07:47 UTC, GazalNebHMRC requested changes

2024-10-01 07:47 UTC, GazalNebHMRC commented on app/v3/validators/resolvers/ResolvePeriodId.scala
> +object ResolveTysTaxYearWithMax extends ResolverSupport {
Please remove ResolveTysTaxYearWithMax from here (in both v3 and v4) and use ResolveTaxYearMinMax from the shared code.

2024-10-01 10:56 UTC, GazalNebHMRC approved these changes

2024-10-01 10:56 UTC, merged